### ISSUE TITLE
summary 태그, flex css 속성 공부 필요 

### ISSUE THREAD

**Issue by vanadis0929** [yoonsujinn/yoonsujinn.github.io#12]
![image](https://github.com/user-attachments/assets/d5184cf5-d9f2-477a-b7a1-9c823a4b115c)

내용을 길게 넣었더니 이렇게 깨져버리는데 css로 이걸 어떻게 해결 할 수 있을까요? 댓글로 남겨주세요

css flex의 속성을 공부하셔야 합니다 flex의 자식들을 width로만 제어하려 하면 이런상황에 대응을 못합니다

**Comment by yoonsujinn** [comment]
flex-shrink: 0; 속성으로 오른쪽 글씨 줄바꿈 되지않도록 수정하였습니다!
