### ISSUE TITLE
전화번호 링크

### ISSUE THREAD

**Issue by vanadis0929** [yoonsujinn/yoonsujinn.github.io#2]
https://github.com/yoonsujinn/yoonsujinn.github.io/blob/0ccd90b2f5f2f0bf1cc47568716df4426d8cca87/greenCard_2.html#L77

전화번호 링크는 

`<a href="tel:1234-5678"> 전화번호 </a>`

식으로 href 안에 tel: 로 들어갑니다 

한번 클릭해보셨다면 이부분을 바로 알았을 건데요...

이 링크를 클릭하면 바로 전화를 거는 앱을 연결시켜줍니다

**Comment by yoonsujinn** [comment]
수정완료!
