### ISSUE TITLE
h1태그

### ISSUE THREAD

**Issue by vanadis0929** [yoonsujinn/yoonsujinn.github.io#4]
https://github.com/yoonsujinn/yoonsujinn.github.io/blob/ede4b9bf9e9fa92eb564b10f05645352300c3c40/greenCard_2.html#L23

nav의 제목이 아니기때문에 얘는 nav 밖으로 나와야합니다 (문서의 전체 제목이 되기 때문)

**Comment by yoonsujinn** [comment]
태그 이름을 바꿔서 수정했습니다!
