### ISSUE TITLE
현재 페이지에대한 안내

### ISSUE THREAD

**Issue by vanadis0929** [yoonsujinn/yoonsujinn.github.io#6]
https://github.com/yoonsujinn/yoonsujinn.github.io/blob/ede4b9bf9e9fa92eb564b10f05645352300c3c40/greenCard_2.html#L75

하나의 페이지에 2가지가 마크업 된 경우에는 이부분에 접근성 처리를 하면 좋습니다 

class="on"만으로는 내가 보고있는 페이지 카테고리가 어딘지를 알기가 어렵습니다 title이나 처리를 해서 현재 활성화된 페이지라고 알려주는것도 좋겠네요

**Comment by yoonsujinn** [comment]
title처리 수정
