### ISSUE TITLE
마크업 문법 오류 

### ISSUE THREAD

**Issue by vanadis0929** [yoonsujinn/yoonsujinn.github.io#8]
![image](https://github.com/user-attachments/assets/349de7b6-ac4e-4220-a133-c1e02fa5fa25)

ul 태그 자식으로 올 수있는 태그는 li뿐입니다 

그 외 문법오류가 많네요;;; 

https://validator.w3.org/nu/?doc=https%3A%2F%2Fyoonsujinn.github.io%2FgreenCard_2.html 에서 참고해보시기 바랍니다

**Comment by yoonsujinn** [comment]
수정완료
